[build]
  base = "frontend"          # Netlify will go into /frontend
  publish = "dist"           # The folder created after `npm run build`
  command = "npm run build"  # Runs your Vite build command

[build.environment]
  NODE_VERSION = "22"        # Ensures correct Node version for compatibility

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200